services:
  wildfly:
    build:
      context: .
      args:
        - login=${wildfly_user_login}
        - password=${wildfly_user_password}
        - db_properties=${db_properties}
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "C:/ITMO/Programming/web-lab-3/build/libs/wars:/opt/jboss/wildfly/standalone/deployments/"

